# Generated by Django 3.1.4 on 2021-01-16 05:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_text', models.CharField(default='', max_length=999)),
                ('video_image', models.URLField(default='', max_length=999)),
                ('video_link', models.URLField(default='', max_length=999)),
                ('slug', models.SlugField(default='', editable=False, max_length=999)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
